apiVersion: v1
kind: Secret
metadata:
  name: backend
  namespace: logistics
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: U2VjdXJlUGFzczEyMyE=  # Base64 for password
  SPRING_DATASOURCE_USERNAME: ZGJhZG1pbg==  
