apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: logistics
spec:
  type: LoadBalancer
  selector:
    name: backend
    project: logistics
    tier: app
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #container-port
